version: '2'
services: 
    cra:
        privileged: true
        security_opt:
            - seccomp:unconfined
        build:
            context: .
            dockerfile: Dockerfile
        volumes: 
            - .:/app:rw
            - /app/node_modules
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
        environment:
            - DISPLAY=:0.0
            - HEADLESS=0
            - DEBUG=*
        env_file: 
            - ./cra.env